### ISSUE TITLE
Проблемы с версткой

### ISSUE THREAD

**Issue by DrZlo13** [flipperdevices/flipperzero-remote-testbench-front#9]
[Mac os catalina safari 13.1, уехал экран](https://i.imgur.com/YO5cb70.png)
на macos mojave та же проблема в сафари и в яндекс браузере 14.12
ios, safari на айпадах и айфонахc ios 12-13 - те же проблемы с позиционированием видео, на ios 11 ещё и проблема с бэкграундом. [iphone 6, iOS 11](https://i.imgur.com/u34NzuH.png)
Так же значительные проблемы на [ipad 4, ios v7](https://i.imgur.com/2O0V5wL.png)

**Comment by lomalkin** [comment]
Сафари
![image](https://user-images.githubusercontent.com/1192479/96735228-039bec00-13c4-11eb-9afa-782ce11f86bd.png)
После нажатия кнопок:
![image](https://user-images.githubusercontent.com/1192479/96735254-0ac2fa00-13c4-11eb-9e81-999f36b480dc.png)

(сам репорт не мой)
выглядит странно, как будто прогрузилось не все

**Comment by imShara** [comment]
i* is the new ie. Тестировать это всё не на чем, похоже придётся прибивать гвоздями.

**Comment by romansavrulin** [comment]
Это Маковский сафари. Скрины мои. На цвета - не смотрите, у меня плагин "Dark theme". Но поломка не из за него

**Comment by imShara** [comment]
Значит какая-то беда с обработкой svg или foreign object в нём на сафари. Коробка в объекта в правильном месте, рендер видео ей не соответствует, можешь посмотреть в инструментах разработчика.

Что касается ios устройств - там видео в том формате, что вещает стенд [вообще работать не будет](https://imshara.github.io/FlipperLab/fuckios)

**Comment by glitchcore** [comment]
Google chrome 86.0.4240.111, Linux mint 19 (cinnamon).

В начале не работает перемещение границы между устройством и консолью, консоль занимает очень мало места:
![image](https://user-images.githubusercontent.com/12886640/97403376-582ff180-1905-11eb-8e01-0bfff1fa1bd6.png)

Далее при появлении сообщений в консоли она занимает почти весь экран:
![image](https://user-images.githubusercontent.com/12886640/97402816-4a2da100-1904-11eb-9d9f-308d0b208500.png)

**Comment by imShara** [comment]
> Google chrome 86.0.4240.111, Linux mint 19 (cinnamon).

Спасибо, увы, проблемы с рачётом flexbox при использовании svg. В обновлении расчёт пропорций и размеров будет полностью переложен с css на js, это решит проблему разных версий браузеров и safari.
